name = "tgpc-ui"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".svelte-kit/cloudflare"

[[r2_buckets]]
binding = "DISPATCH"
bucket_name = "tgpc"
